version: "3.9"

services:
  solis-cloud-scraper:
    container_name: solis-cloud-scraper
    build: ./app
    environment:
      - TZ=Europe/London
      - SOLIS_USERNAME=${SOLIS_USERNAME}
      - SOLIS_PASSWORD=${SOLIS_PASSWORD}
    ports:
      - "8080:8080"
    restart: always
    init: true
